# Generated by Django 4.2.13 on 2024-06-11 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DataSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("assistant_id", models.PositiveBigIntegerField()),
                ("name", models.CharField(max_length=255)),
                ("data_type", models.CharField(default="", max_length=255)),
                ("source_url", models.CharField(default="", max_length=255)),
                ("category", models.CharField(default="", max_length=255)),
                ("provider_type", models.CharField(default="", max_length=255)),
                ("extra_info", models.JSONField(default={})),
                (
                    "description",
                    models.TextField(
                        default="",
                        help_text="Description of the data source if required",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DataSourceLogs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("data_source_id", models.PositiveBigIntegerField()),
                ("assistant_id", models.PositiveBigIntegerField()),
                ("name", models.CharField(max_length=255)),
                ("data_type", models.CharField(default="", max_length=255)),
                ("source_url", models.CharField(default="", max_length=255)),
                ("category", models.CharField(default="", max_length=255)),
                ("provider_type", models.CharField(default="", max_length=255)),
                ("extra_info", models.JSONField(default={})),
                (
                    "description",
                    models.TextField(
                        default="",
                        help_text="Description of the data source if required",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
