# Generated by Django 4.2.13 on 2024-06-12 04:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("training", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasource",
            name="version",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="datasource",
            name="category",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="datasource",
            name="data_type",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="datasource",
            name="description",
            field=models.TextField(
                help_text="Description of the data source if required"
            ),
        ),
        migrations.AlterField(
            model_name="datasource",
            name="provider_type",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="datasource",
            name="source_url",
            field=models.CharField(max_length=255),
        ),
    ]
